import { useState, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/app-client';

const EXPECTED_TABLES = ['profiles', 'spaces', 'items', 'habits', 'habit_entries', 'user_preferences', 'notifications', 'scheduled_reminders'] as const;

export interface TableHealth {
  name: string;
  accessible: boolean;
  error?: string;
}

export interface SupabaseHealthResult {
  projectId: string;
  projectUrl: string;
  // True if the Supabase server responded (auth endpoint was reachable).
  serverReachable: boolean;
  // True only if a valid session exists AND RLS queries succeed for the current user.
  dataAccessible: boolean;
  spacesCount: number | null;
  itemsCount: number | null;
  tables: TableHealth[];
  checkedAt: Date;
}

export function useSupabaseHealth() {
  const [result, setResult] = useState<SupabaseHealthResult | null>(null);
  const [checking, setChecking] = useState(false);

  const projectUrl = import.meta.env.VITE_SUPABASE_URL as string;
  const projectId = projectUrl ? new URL(projectUrl).hostname.split('.')[0] : 'unknown';

  const check = useCallback(async () => {
    setChecking(true);
    try {
      // Auth call determines both server reachability and session validity.
      // If this throws, the server is unreachable. If it returns (even with no user),
      // the server responded — so serverReachable = true.
      const { data: { user }, error: authError } = await supabase.auth.getUser();
      const serverReachable = true; // reaching this line means the auth endpoint responded

      // Test basic DB reachability — any non-network response means the Supabase
      // endpoint is up. We distinguish network failures (no response at all, e.g.
      // "Failed to fetch") from DB-level errors (auth failures, RLS, etc.) so that
      // "reachable" truly means the server is responding.
      const pingResult = await supabase.from('profiles').select('id').limit(1);
      const isNetworkError = !!pingResult.error && (
        pingResult.error.message?.includes('Failed to fetch') ||
        pingResult.error.message?.includes('NetworkError') ||
        pingResult.error.message?.includes('fetch failed') ||
        pingResult.error.message?.includes('ERR_INTERNET_DISCONNECTED') ||
        // Generic offline indicator: no HTTP status code received
        (pingResult.error as any)?.status == null
      );
      // reachable = server responded at all (DB errors are OK; network errors are not)
      // Note: PGRST116 ("no rows when using .single()") is intentionally NOT treated as
      // a special success case. The `.limit(1)` query used here never generates PGRST116
      // in practice; removing the exception makes the check explicit and correct.
      const reachable = !isNetworkError;

      // Check whether user's actual data is accessible (not just that the DB responds).
      // "reachable" only means the server is up; "userDataAccessible" confirms RLS passes
      // and the authenticated user can actually read their own spaces and items.
      let userDataAccessible = false;
      let userSpaceCount: number | null = null;
      let userItemCount: number | null = null;
      let dataAccessible = false;
      let spacesCount: number | null = null;
      let itemsCount: number | null = null;

      if (!authError && user) {
        const [spacesCheck, itemsCheck] = await Promise.all([
          supabase.from('spaces').select('*', { count: 'exact', head: true }).eq('user_id', user.id),
          supabase.from('items').select('*', { count: 'exact', head: true }).eq('user_id', user.id),
        ]);
        // No error means RLS passed and user data is accessible
        dataAccessible = !spacesCheck.error && !itemsCheck.error;
        spacesCount = spacesCheck.error ? null : (spacesCheck.count ?? 0);
        itemsCount = itemsCheck.error ? null : (itemsCheck.count ?? 0);
      }

      // Check each expected table for existence and accessibility.
      // A table is considered accessible when the query returns no error.
      // Crucially, we do NOT treat PGRST116 ("no rows") as a success indicator:
      // - With .limit(1) (used here), PGRST116 is not generated by PostgREST.
      // - If it were, it could mask RLS policies blocking all row access.
      // Only error code 42P01 (table does not exist) is a definitive failure.
      const tables: TableHealth[] = await Promise.all(
        EXPECTED_TABLES.map(async (name) => {
          const { error } = await supabase.from(name as any).select('id').limit(1);
          // error code 42P01 = table does not exist
          if (!error) {
            return { name, accessible: true };
          }
          return { name, accessible: false, error: error.message };
        })
      );

      setResult({ projectId, projectUrl, serverReachable, dataAccessible, spacesCount, itemsCount, tables, checkedAt: new Date() });
    } catch (err) {
      setResult({
        projectId,
        projectUrl,
        serverReachable: false,
        dataAccessible: false,
        spacesCount: null,
        itemsCount: null,
        tables: EXPECTED_TABLES.map(name => ({ name, accessible: false, error: 'Connection failed' })),
        checkedAt: new Date(),
      });
    } finally {
      setChecking(false);
    }
  }, [projectId, projectUrl]);

  return { result, checking, check, projectId, projectUrl };
}
